#!/usr/bin/env php
<?php

use think\App;

require __DIR__ . '/../../vendor/autoload.php';

$app = new App(__DIR__);

$app->console->addCommands([
    \lychee\worker\command\Server::class,
    \lychee\worker\command\WorkerDev::class,
    \lychee\worker\command\WorkerStatus::class,
    \lychee\worker\command\WorkerChild::class,
    \lychee\worker\command\WorkerQueue::class,
]);

$app->console->run();